language: node_js
node_js:
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.5"
  - "3.0"
  - "3.3"
  - "4.0"
  - "4.3"
  - "5.0"
  - "5.7"
notifications:
  slack:
    on_success: never
    on_failure: always
sudo: false
deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  on:
    - tags: true
