language: node_js
node_js:
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.8"
  - "5.12"
  - "6.11"
  - "7.10"
  - "8.5"
notifications:
  slack:
    on_success: never
    on_failure: always
sudo: false
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    tags: true
